### ISSUE TITLE
AttributeError: 'ElementTree' object has no attribute 'getiterator'

### ISSUE THREAD

**Issue by Arjun31415** [gabrielbarbosanascimento/Up-Clock#26]
On Ubuntu 21.10 when I try to install and run 
```bash
$ sudo add-apt-repository ppa:apandada1/up-clock
$ sudo apt-get update
$ sudo apt-get install up-clock
```
```bash
up-clock
```

This is the error-

```bash
Traceback (most recent call last):
  File "/usr/bin/up-clock", line 48, in <module>
    up_clock.main()
  File "/usr/lib/python3/dist-packages/up_clock/__init__.py", line 45, in main
    window = UpClockWindow.UpClockWindow()
  File "/usr/lib/python3/dist-packages/up_clock_lib/Window.py", line 47, in __new__
    builder = get_builder('UpClockWindow')
  File "/usr/lib/python3/dist-packages/up_clock_lib/helpers.py", line 43, in get_builder
    builder.add_from_file(ui_filename)
  File "/usr/lib/python3/dist-packages/up_clock_lib/Builder.py", line 88, in add_from_file
    ele_widgets = tree.getiterator("object")
AttributeError: 'ElementTree' object has no attribute 'getiterator'
```
also upclock does not load when clicking it in application list

**Comment by apandada1** [comment]
Fixed in https://github.com/gabrielbarbosanascimento/Up-Clock/commit/97c4dfffb5d5b7d6ee7cb44bbd4b6f82493a3d18
The fixed version for Ubuntu 22.04+ is available in the Launchpad PPA.
